# Generated by Django 5.1.7 on 2025-04-24 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/Extras')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/Extras')),
            ],
        ),
        migrations.CreateModel(
            name='NewRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('القامشلي', 'القامشلي'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة')),
                ('town', models.CharField(blank=True, max_length=30, null=True, verbose_name='المدينة او البلدة')),
                ('type', models.CharField(blank=True, choices=[('مزرعة', 'مزرعة'), ('فيلّا', 'فيلّا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='ملاحظات')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('city', models.CharField(choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('القامشلي', 'القامشلي'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة')),
                ('town', models.CharField(default='', max_length=30, verbose_name='المنطقة')),
                ('type', models.CharField(choices=[('مزرعة', 'مزرعة'), ('فيلّا', 'فيلّا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار')),
                ('max_members', models.IntegerField(default=0, verbose_name='عدد الاشخاص المسموح')),
                ('rooms', models.IntegerField(default=0, verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='عدد الحمامات')),
                ('pool', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='هل يوجد مسبح؟')),
                ('period', models.CharField(choices=[('بالليلة', 'بالليلة'), ('بالشهر', 'بالشهر')], max_length=30, null=True, verbose_name='باليوم او بالشهر؟')),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/properties')),
                ('describtion', models.TextField(default='')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('name', models.CharField(max_length=255)),
                ('basics', models.ManyToManyField(to='reservations.basics')),
                ('extras', models.ManyToManyField(to='reservations.extras')),
            ],
        ),
        migrations.CreateModel(
            name='MyRealEstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrealestates', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
                ('realestate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myrealestates_list', to='reservations.realestate', verbose_name='العقار')),
            ],
        ),
        migrations.CreateModel(
            name='Favourits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='الزبون')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_list', to='reservations.realestate', verbose_name='العقار')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/properties', verbose_name='الصورة')),
                ('realestate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('DayOff', 'DayOff')], default='', max_length=30)),
                ('assigned_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to=settings.AUTH_USER_MODEL)),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_periods', to='reservations.realestate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_periods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('self', 'Self'), ('group_request', 'Group Request'), ('assignment', 'Assignment'), ('result', 'Result')], default='self', max_length=30)),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_to', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservationperiod')),
            ],
        ),
        migrations.CreateModel(
            name='MyReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to='reservations.realestate', verbose_name='العقار')),
                ('reservationPeriod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('real_estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reservations.realestate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Second_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('real_estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_review', to='reservations.realestate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
