# Generated by Django 5.1.7 on 2025-05-02 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('city', models.CharField(choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('القامشلي', 'القامشلي'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة')),
                ('town', models.CharField(default='', max_length=30, verbose_name='المنطقة')),
                ('type', models.CharField(choices=[('مزرعة', 'مزرعة'), ('فيلّا', 'فيلّا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار')),
                ('max_members', models.IntegerField(default=0, verbose_name='عدد الاشخاص المسموح')),
                ('rooms', models.IntegerField(default=0, verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='عدد الحمامات')),
                ('period', models.CharField(choices=[('بالليلة', 'بالليلة'), ('بالشهر', 'بالشهر')], max_length=30, null=True, verbose_name='باليوم او بالشهر؟')),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/properties')),
                ('description', models.TextField(default='')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('basics', models.ManyToManyField(to='reservations.basics')),
                ('extras', models.ManyToManyField(to='reservations.extras')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myrealestates', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/properties', verbose_name='الصورة')),
                ('realestate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.realestate')),
            ],
        ),
    ]
