# Generated by Django 5.1.7 on 2025-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiod',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('DayOff', 'DayOff')], default='pending', max_length=30),
        ),
    ]
