# Generated by Django 5.1.7 on 2025-04-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservationperiod_assigned_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='name',
        ),
    ]
