# Generated by Django 5.1.7 on 2025-04-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_realestate_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='description',
        ),
        migrations.AddField(
            model_name='notifications',
            name='describtion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
