# Generated by Django 5.1.7 on 2025-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_newrealestate_assigned_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_reservation',
            name='notification_type',
            field=models.CharField(choices=[('accepted_user', 'accepted_user'), ('rejected_user', 'rejected_user'), ('still_pending_user', 'still_pending_user'), ('message_to_Owner', 'message_to_Owner')], default='still_pending_user', max_length=50),
        ),
    ]
