# Generated by Django 5.1.7 on 2025-04-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_notifications_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationperiod',
            name='assigned_handler',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user_to',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationperiod',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('DayOff', 'DayOff')], default='', max_length=30),
        ),
    ]
