# Generated by Django 5.1.7 on 2025-05-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_notifications_reservation_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_reservation',
            name='notification_type',
            field=models.CharField(choices=[('accepted_user', 'accepted_user'), ('rejected_user', 'rejected_user'), ('still_pending_user', 'still_pending_user'), ('res_accepted_to_Owner', 'res_accepted_to_Owner'), ('res_rejected_to_Owner', 'res_rejected_to_Owner'), ('res_pending_to_Owner', 'res_pending_to_Owner')], default='still_pending_user', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservationperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_periods', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الحجز'),
        ),
    ]
