# Generated by Django 5.1.7 on 2025-05-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_notifications_reservation_notification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basics',
            old_name='description',
            new_name='describtion',
        ),
        migrations.RenameField(
            model_name='extras',
            old_name='description',
            new_name='describtion',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='notifications_group',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='notifications_reservation',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='notifications_reservation_group',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='description',
            new_name='describtion',
        ),
        migrations.RenameField(
            model_name='reservationperiod',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='reservationrejection',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='second_review',
            old_name='created_at',
            new_name='createAt',
        ),
    ]
