# Generated by Django 5.1.7 on 2025-05-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_rename_description_basics_describtion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyReservations',
        ),
    ]
