# Generated by Django 5.1.7 on 2025-03-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_realestate_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d', verbose_name='الصورة')),
                ('realestate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.realestate')),
            ],
        ),
    ]
