# Generated by Django 5.1.7 on 2025-05-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_delete_myreservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiod',
            name='realestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate', to='reservations.realestate'),
        ),
    ]
