# Generated by Django 5.1.7 on 2025-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20250424_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='reservation',
        ),
        migrations.AddField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
