# Generated by Django 5.1.7 on 2025-03-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_realestate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/properties'),
        ),
        migrations.AlterField(
            model_name='realestate_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/properties', verbose_name='الصورة'),
        ),
    ]
