# Generated by Django 5.1.7 on 2025-04-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_remove_notifications_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user_from',
        ),
    ]
