# Generated by Django 5.1.7 on 2025-04-24 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_notifications_user_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notifications',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservationperiod'),
        ),
        migrations.CreateModel(
            name='Notifications_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.TextField(default='')),
                ('notification_type', models.CharField(choices=[('self', 'Self'), ('group_request', 'Group Request'), ('assignment', 'Assignment'), ('result', 'Result')], default='self', max_length=30)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_reservation', to='reservations.reservationperiod')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_reservation_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
