# Generated by Django 5.1.7 on 2025-04-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_notifications_createat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='createAt',
        ),
        migrations.RemoveField(
            model_name='notifications_reservation',
            name='createAt',
        ),
    ]
