# Generated by Django 5.1.7 on 2025-04-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_notifications_reservation_createat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications_reservation',
            name='createAt',
        ),
        migrations.RemoveField(
            model_name='notifications_reservation',
            name='reservation',
        ),
    ]
