# Generated by Django 5.1.7 on 2025-04-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_remove_notifications_reservation_createat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications_reservation',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications_reservation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_reservation', to='reservations.reservationperiod'),
        ),
    ]
