# Generated by Django 5.1.7 on 2025-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_reservationperiod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiod',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='', max_length=30),
        ),
    ]
