# Generated by Django 5.1.7 on 2025-04-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_notifications_createat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='reservation',
        ),
    ]
