# Generated by Django 5.1.7 on 2025-03-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('city', models.CharField(choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('القامشلي', 'القامشلي'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة')),
                ('town', models.CharField(default='', max_length=30, verbose_name='المنطقة')),
                ('type', models.CharField(choices=[('مزرعة', 'مزرعة'), ('فيلا', 'فيلا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار')),
                ('max_members', models.IntegerField(default=0, verbose_name='عدد الاشخاص المسموح')),
                ('rooms', models.IntegerField(default=0, verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='عدد الحمامات')),
                ('pool', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='هل يوجد مسبح؟')),
                ('period', models.CharField(choices=[('بالليلة', 'بالليلة'), ('بالشهر', 'بالشهر')], max_length=30, null=True, verbose_name='باليوم او بالشهر؟')),
            ],
        ),
    ]
