# Generated by Django 5.1.7 on 2025-03-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.CharField(max_length=50)),
                ('real_estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='reservations.realestate')),
            ],
        ),
    ]
