# Generated by Django 5.1.7 on 2025-03-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_realestate_ratings_alter_comments_real_estate_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='real_estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reservations.realestate'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
