# Generated by Django 5.1.7 on 2025-03-20 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_second_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_list', to='reservations.realestate', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='الزبون')),
            ],
        ),
        migrations.CreateModel(
            name='MyRealEstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrealestates_list', to='reservations.realestate', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrealestates', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
            ],
        ),
        migrations.CreateModel(
            name='MyReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to='reservations.realestate', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='صاحب العقار')),
            ],
        ),
    ]
