# Generated by Django 5.1.7 on 2025-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_favourits_myrealestates_myreservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
