# Generated by Django 5.1.7 on 2025-03-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_realestate_photo_alter_realestate_images_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrealestate',
            name='city',
            field=models.CharField(blank=True, choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('الرقة', 'الرقة'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='newrealestate',
            name='type',
            field=models.CharField(blank=True, choices=[('مزرعة', 'مزرعة'), ('فيلّا', 'فيلّا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='city',
            field=models.CharField(choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('الرقة', 'الرقة'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.CharField(choices=[('مزرعة', 'مزرعة'), ('فيلّا', 'فيلّا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.realestate', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_user', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
