# Generated by Django 5.1.7 on 2025-04-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_newrealestate_city_alter_realestate_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/Extras')),
            ],
        ),
        migrations.RemoveField(
            model_name='extras',
            name='real_estate',
        ),
        migrations.AddField(
            model_name='extras',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/Extras'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='extras',
            field=models.ManyToManyField(null=True, to='reservations.extras'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='basics',
            field=models.ManyToManyField(null=True, to='reservations.basics'),
        ),
    ]
