# Generated by Django 5.1.7 on 2025-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_basics_remove_extras_real_estate_extras_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
    ]
