# Generated by Django 5.1.7 on 2025-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_reservationperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationperiod',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('rejected', 'مرفوض'), ('accepted', 'مقبول')], default='', max_length=30),
        ),
    ]
