# Generated by Django 5.1.7 on 2025-03-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_person_city_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
