# Generated by Django 5.1.7 on 2025-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_person_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
